language: nix

env:
  - EMACS_CI=emacs-26-1
  - EMACS_CI=emacs-26-2
  - EMACS_CI=emacs-26-3
  - EMACS_CI=emacs-snapshot

matrix:
  allow_failures:
    - env: EMACS_CI=emacs-snapshot

install:
  - bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)

script:
  - export HOME=$PWD/..
  - ln -s dotemacs ../.emacs.d
  - |-
    emacs -nw --batch \
          -eval '(let ((debug-on-error t)
                       (url-show-status nil)
                       (user-emacs-directory default-directory)
                       (user-init-file (expand-file-name "init.el"))
                       (load-path (delq default-directory load-path)))
                   (load-file user-init-file)
                   (run-hooks (quote after-init-hook)))' && \
    echo "Startup succeeded."

notifications:
  email:
    on_success: never
    on_failure: always
