language: nix

os:
  - osx
  - linux

env:
  - EMACS_CI=emacs-26-1
  - EMACS_CI=emacs-26-2
  - EMACS_CI=emacs-26-3
  - EMACS_CI=emacs-snapshot

install:
  - bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)

script:
  # If the build timeout, you can remove "straight/versions/default.el" in order to use shallow-clone.
  - export HOME=$PWD/..
  - ln -s dotemacs ../.emacs.d
  - |-
    emacs -nw --batch \
          -eval '(let ((debug-on-error t)
                       (url-show-status nil)
                       (user-emacs-directory default-directory)
                       (user-init-file (expand-file-name "init.el"))
                       (load-path (delq default-directory load-path)))
                   (load-file user-init-file)
                   (run-hooks (quote after-init-hook))
                   (my-deploy-ghpage))' && \
    echo "Startup succeeded."

before_deploy:
  - mkdir -p docs
  - mv README.html docs/index.html
  - curl -fsSkL --retry 9 https://orgmode.org/worg/style/worg.css -o docs/style.css

deploy:
  provider: pages
  local_dir: docs
  target_branch: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: master
    condition: os = linux AND $EMACS_CI = emacs-26-1

notifications:
  email:
    on_success: never
    on_failure: always
