language: generic
dist: xenial

env:
  global:
    CURL="curl -fsSkL --retry 9 --retry-delay 9"
  matrix:
    - EMACS_VERSION=26
    - EMACS_VERSION=master
  allow_failure:
    env: EMACS_VERSION=master

before_install:
  - sudo apt-get install libgnutls-dev -y

install:
  # Install Emacs to /tmp/emacs
  - $CURL -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar xf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs
  - $EMACS --version

script:
  - rm straight/versions/default.el
  - $EMACS -batch --load=init.el --eval '(message "Test Passed.")'

before_deploy:
  - $EMACS -batch --load=init.el  --funcall=my-deploy-ghpage
  - mkdir -p docs
  - mv README.html docs/index.html
  - $CURL https://orgmode.org/worg/style/worg.css -o docs/style.css

deploy:
  provider: pages
  local_dir: docs
  target_branch: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: master
    condition: $EMACS_VERSION=26

notifications:
  email:
    on_success: never
    on_failure: always
