language: generic
dist: trusty

env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"
  matrix:
    - EMACS_VERSION=26.1
    - EMACS_VERSION=26.2
    - EMACS_VERSION=master
  allow_failures:
    env: EMACS_VERSION=master

install:
  # Install Emacs to /tmp/emacs
  - $CURL -O https://github.com/npostavs/emacs-travis/releases/download/bins/emacs-bin-${EMACS_VERSION}.tar.gz
  - tar -xaf emacs-bin-${EMACS_VERSION}.tar.gz -C /
  - export EMACS=/tmp/emacs/bin/emacs
  - $EMACS --version

script:
  # If the build timeout, you can remove "straight/versions/default.el" in order to use shallow-clone.
  - $EMACS -batch --load=init.el --eval '(message "Test Passed.")'

before_deploy:
  - $EMACS -batch --load=init.el --funcall=my-deploy-ghpage
  - mkdir -p docs
  - mv README.html docs/index.html
  - $CURL https://orgmode.org/worg/style/worg.css -o docs/style.css

deploy:
  provider: pages
  local_dir: docs
  target_branch: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: master
    condition: $EMACS_VERSION = 26.1

notifications:
  email:
    on_success: never
    on_failure: always
